name: RadarrAPI
targets:
  RadarrAPI:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: []
    info:
      path: ./Info.plist
      version: 3.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
