name: thriftwood
version: 11.0.0
confinement: strict
base: core22
# Required but managed manually via Snapcraft dashboard
summary: summary
description: description
slots:
  dbus-thriftwood:
    interface: dbus
    bus: session
    name: app.thriftwood.thriftwood
apps:
  thriftwood:
    command: thriftwood
    extensions:
    - gnome
    plugs:
    - home
    - network
    slots:
    - dbus-thriftwood
parts:
  zenity:
    plugin: nil
    stage-packages:
    - zenity
  thriftwood:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
