# OpenAPI Generator Configuration for Radarr API
# Generator: swift6 (STABLE)
# Target: Swift 6.x with URLSession

# HTTP Client Library
library: urlsession

# Project Configuration
projectName: RadarrAPI
apiNamePrefix: Radarr
useSPMFileStructure: false
swiftPackagePath: ""

# Response Handling
responseAs: AsyncAwait

# Model Configuration
hashableModels: true
identifiableModels: true
validatable: true
generateModelAdditionalProperties: true
sortModelPropertiesByRequiredFlag: true

# Enum Handling
enumUnknownDefaultCase: true
oneOfUnknownDefaultCase: false

# Code Generation
hideGenerationTimestamp: false
ensureUniqueParams: true
sortParamsByRequiredFlag: true

# Access Control
# nonPublicApi: false  # Use default (public APIs)

# Additional Options
# useClasses: false  # Use structs (default)
# readonlyProperties: false
# objcCompatible: false
