//
// RadarrCalendarAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RadarrCalendarAPI {

    /**

     - parameter start: (query)  (optional)
     - parameter end: (query)  (optional)
     - parameter unmonitored: (query)  (optional, default to false)
     - parameter tags: (query)  (optional, default to "")
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [MovieResource]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV3CalendarGet(start: Date? = nil, end: Date? = nil, unmonitored: Bool? = nil, tags: String? = nil, apiConfiguration: RadarrAPIAPIConfiguration = RadarrAPIAPIConfiguration.shared) async throws(ErrorResponse) -> [MovieResource] {
        return try await apiV3CalendarGetWithRequestBuilder(start: start, end: end, unmonitored: unmonitored, tags: tags, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v3/calendar
     - parameter start: (query)  (optional)
     - parameter end: (query)  (optional)
     - parameter unmonitored: (query)  (optional, default to false)
     - parameter tags: (query)  (optional, default to "")
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[MovieResource]> 
     */
    open class func apiV3CalendarGetWithRequestBuilder(start: Date? = nil, end: Date? = nil, unmonitored: Bool? = nil, tags: String? = nil, apiConfiguration: RadarrAPIAPIConfiguration = RadarrAPIAPIConfiguration.shared) -> RequestBuilder<[MovieResource]> {
        let localVariablePath = "/api/v3/calendar"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start": (wrappedValue: start?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "end": (wrappedValue: end?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "unmonitored": (wrappedValue: unmonitored?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "tags": (wrappedValue: tags?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[MovieResource]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
