//
// AddMovieOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddMovieOptions: Sendable, Codable, ParameterConvertible, Hashable {

    public var ignoreEpisodesWithFiles: Bool?
    public var ignoreEpisodesWithoutFiles: Bool?
    public var monitor: MonitorTypes?
    public var searchForMovie: Bool?
    public var addMethod: AddMovieMethod?

    public init(ignoreEpisodesWithFiles: Bool? = nil, ignoreEpisodesWithoutFiles: Bool? = nil, monitor: MonitorTypes? = nil, searchForMovie: Bool? = nil, addMethod: AddMovieMethod? = nil) {
        self.ignoreEpisodesWithFiles = ignoreEpisodesWithFiles
        self.ignoreEpisodesWithoutFiles = ignoreEpisodesWithoutFiles
        self.monitor = monitor
        self.searchForMovie = searchForMovie
        self.addMethod = addMethod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ignoreEpisodesWithFiles
        case ignoreEpisodesWithoutFiles
        case monitor
        case searchForMovie
        case addMethod
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ignoreEpisodesWithFiles, forKey: .ignoreEpisodesWithFiles)
        try container.encodeIfPresent(ignoreEpisodesWithoutFiles, forKey: .ignoreEpisodesWithoutFiles)
        try container.encodeIfPresent(monitor, forKey: .monitor)
        try container.encodeIfPresent(searchForMovie, forKey: .searchForMovie)
        try container.encodeIfPresent(addMethod, forKey: .addMethod)
    }
}

