//
// AlternativeTitleResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlternativeTitleResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var sourceType: SourceType?
    public var movieMetadataId: Int?
    public var title: String?
    public var cleanTitle: String?

    public init(id: Int? = nil, sourceType: SourceType? = nil, movieMetadataId: Int? = nil, title: String? = nil, cleanTitle: String? = nil) {
        self.id = id
        self.sourceType = sourceType
        self.movieMetadataId = movieMetadataId
        self.title = title
        self.cleanTitle = cleanTitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case sourceType
        case movieMetadataId
        case title
        case cleanTitle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(sourceType, forKey: .sourceType)
        try container.encodeIfPresent(movieMetadataId, forKey: .movieMetadataId)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(cleanTitle, forKey: .cleanTitle)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AlternativeTitleResource: Identifiable {}
