//
// BackupType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BackupType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case scheduled = "scheduled"
    case manual = "manual"
    case update = "update"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
