//
// BackupResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BackupResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var name: String?
    public var path: String?
    public var type: BackupType?
    public var size: Int64?
    public var time: Date?

    public init(id: Int? = nil, name: String? = nil, path: String? = nil, type: BackupType? = nil, size: Int64? = nil, time: Date? = nil) {
        self.id = id
        self.name = name
        self.path = path
        self.type = type
        self.size = size
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case path
        case type
        case size
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(time, forKey: .time)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BackupResource: Identifiable {}
