//
// CertificateValidationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CertificateValidationType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case enabled = "enabled"
    case disabledforlocaladdresses = "disabledForLocalAddresses"
    case disabled = "disabled"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
