//
// ColonReplacementFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ColonReplacementFormat: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case delete = "delete"
    case dash = "dash"
    case spacedash = "spaceDash"
    case spacedashspace = "spaceDashSpace"
    case smart = "smart"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
