//
// CommandStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CommandStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case queued = "queued"
    case started = "started"
    case completed = "completed"
    case failed = "failed"
    case aborted = "aborted"
    case cancelled = "cancelled"
    case orphaned = "orphaned"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
