//
// CommandPriority.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CommandPriority: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case normal = "normal"
    case high = "high"
    case low = "low"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
