//
// CommandResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CommandResult: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case unknown = "unknown"
    case successful = "successful"
    case unsuccessful = "unsuccessful"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
