//
// CustomFormatBulkResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CustomFormatBulkResource: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    public var ids: Set<Int>?
    public var includeCustomFormatWhenRenaming: Bool?

    public init(ids: Set<Int>? = nil, includeCustomFormatWhenRenaming: Bool? = nil) {
        self.ids = ids
        self.includeCustomFormatWhenRenaming = includeCustomFormatWhenRenaming
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
        case includeCustomFormatWhenRenaming
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ids, forKey: .ids)
        try container.encodeIfPresent(includeCustomFormatWhenRenaming, forKey: .includeCustomFormatWhenRenaming)
    }
}

