//
// CustomFilterResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CustomFilterResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var type: String?
    public var label: String?
    public var filters: [JSONValue]?

    public init(id: Int? = nil, type: String? = nil, label: String? = nil, filters: [JSONValue]? = nil) {
        self.id = id
        self.type = type
        self.label = label
        self.filters = filters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case label
        case filters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(filters, forKey: .filters)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CustomFilterResource: Identifiable {}
