//
// DownloadProtocol.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum DownloadProtocol: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case unknown = "unknown"
    case usenet = "usenet"
    case torrent = "torrent"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
