//
// ExtraFileType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ExtraFileType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case subtitle = "subtitle"
    case metadata = "metadata"
    case other = "other"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
