//
// FileDateType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum FileDateType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _none = "none"
    case cinemas = "cinemas"
    case release = "release"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
