//
// HealthCheckResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum HealthCheckResult: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case ok = "ok"
    case notice = "notice"
    case warning = "warning"
    case error = "error"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
