//
// ImportRejectionResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportRejectionResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var reason: String?
    public var type: RejectionType?

    public init(reason: String? = nil, type: RejectionType? = nil) {
        self.reason = reason
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

