//
// ImportListExclusionBulkResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportListExclusionBulkResource: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    public var ids: Set<Int>?

    public init(ids: Set<Int>? = nil) {
        self.ids = ids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ids, forKey: .ids)
    }
}

