//
// LocalizationLanguageResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LocalizationLanguageResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var identifier: String?

    public init(identifier: String? = nil) {
        self.identifier = identifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identifier, forKey: .identifier)
    }
}

