//
// LogFileResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LogFileResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var filename: String?
    public var lastWriteTime: Date?
    public var contentsUrl: String?
    public var downloadUrl: String?

    public init(id: Int? = nil, filename: String? = nil, lastWriteTime: Date? = nil, contentsUrl: String? = nil, downloadUrl: String? = nil) {
        self.id = id
        self.filename = filename
        self.lastWriteTime = lastWriteTime
        self.contentsUrl = contentsUrl
        self.downloadUrl = downloadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case filename
        case lastWriteTime
        case contentsUrl
        case downloadUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(filename, forKey: .filename)
        try container.encodeIfPresent(lastWriteTime, forKey: .lastWriteTime)
        try container.encodeIfPresent(contentsUrl, forKey: .contentsUrl)
        try container.encodeIfPresent(downloadUrl, forKey: .downloadUrl)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension LogFileResource: Identifiable {}
