//
// MediaCoverTypes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MediaCoverTypes: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case unknown = "unknown"
    case poster = "poster"
    case banner = "banner"
    case fanart = "fanart"
    case screenshot = "screenshot"
    case headshot = "headshot"
    case clearlogo = "clearlogo"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
