//
// MetadataConfigResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MetadataConfigResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var certificationCountry: TMDbCountryCode?

    public init(id: Int? = nil, certificationCountry: TMDbCountryCode? = nil) {
        self.id = id
        self.certificationCountry = certificationCountry
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case certificationCountry
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(certificationCountry, forKey: .certificationCountry)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension MetadataConfigResource: Identifiable {}
