//
// Modifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum Modifier: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _none = "none"
    case regional = "regional"
    case screener = "screener"
    case rawhd = "rawhd"
    case brdisk = "brdisk"
    case remux = "remux"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
