//
// MonitorTypes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MonitorTypes: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case movieonly = "movieOnly"
    case movieandcollection = "movieAndCollection"
    case _none = "none"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
