//
// MovieStatusType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MovieStatusType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case tba = "tba"
    case announced = "announced"
    case incinemas = "inCinemas"
    case released = "released"
    case deleted = "deleted"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
