//
// MovieRuntimeFormatType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MovieRuntimeFormatType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case hoursminutes = "hoursMinutes"
    case minutes = "minutes"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
