//
// MovieStatisticsResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MovieStatisticsResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var movieFileCount: Int?
    public var sizeOnDisk: Int64?
    public var releaseGroups: [String]?

    public init(movieFileCount: Int? = nil, sizeOnDisk: Int64? = nil, releaseGroups: [String]? = nil) {
        self.movieFileCount = movieFileCount
        self.sizeOnDisk = sizeOnDisk
        self.releaseGroups = releaseGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case movieFileCount
        case sizeOnDisk
        case releaseGroups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(movieFileCount, forKey: .movieFileCount)
        try container.encodeIfPresent(sizeOnDisk, forKey: .sizeOnDisk)
        try container.encodeIfPresent(releaseGroups, forKey: .releaseGroups)
    }
}

