//
// MovieCollectionResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MovieCollectionResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var title: String?
    public var tmdbId: Int?

    public init(title: String? = nil, tmdbId: Int? = nil) {
        self.title = title
        self.tmdbId = tmdbId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case tmdbId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(tmdbId, forKey: .tmdbId)
    }
}

