//
// PrivacyLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PrivacyLevel: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case normal = "normal"
    case password = "password"
    case apikey = "apiKey"
    case username = "userName"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
