//
// ProfileFormatItemResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProfileFormatItemResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var format: Int?
    public var name: String?
    public var score: Int?

    public init(id: Int? = nil, format: Int? = nil, name: String? = nil, score: Int? = nil) {
        self.id = id
        self.format = format
        self.name = name
        self.score = score
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case format
        case name
        case score
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(score, forKey: .score)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProfileFormatItemResource: Identifiable {}
