//
// ProviderMessageType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ProviderMessageType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case info = "info"
    case warning = "warning"
    case error = "error"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
