//
// ProxyType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ProxyType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case http = "http"
    case socks4 = "socks4"
    case socks5 = "socks5"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
