//
// QualityDefinitionResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QualityDefinitionResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var quality: Quality?
    public var title: String?
    public var weight: Int?
    public var minSize: Double?
    public var maxSize: Double?
    public var preferredSize: Double?

    public init(id: Int? = nil, quality: Quality? = nil, title: String? = nil, weight: Int? = nil, minSize: Double? = nil, maxSize: Double? = nil, preferredSize: Double? = nil) {
        self.id = id
        self.quality = quality
        self.title = title
        self.weight = weight
        self.minSize = minSize
        self.maxSize = maxSize
        self.preferredSize = preferredSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case quality
        case title
        case weight
        case minSize
        case maxSize
        case preferredSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(quality, forKey: .quality)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(weight, forKey: .weight)
        try container.encodeIfPresent(minSize, forKey: .minSize)
        try container.encodeIfPresent(maxSize, forKey: .maxSize)
        try container.encodeIfPresent(preferredSize, forKey: .preferredSize)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QualityDefinitionResource: Identifiable {}
