//
// QueueBulkResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QueueBulkResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var ids: [Int]?

    public init(ids: [Int]? = nil) {
        self.ids = ids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ids, forKey: .ids)
    }
}

