//
// RatingChild.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RatingChild: Sendable, Codable, ParameterConvertible, Hashable {

    public var votes: Int?
    public var value: Double?
    public var type: RatingType?

    public init(votes: Int? = nil, value: Double? = nil, type: RatingType? = nil) {
        self.votes = votes
        self.value = value
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case votes
        case value
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(votes, forKey: .votes)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

