//
// RejectionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RejectionType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case permanent = "permanent"
    case temporary = "temporary"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
