//
// RemotePathMappingResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RemotePathMappingResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var host: String?
    public var remotePath: String?
    public var localPath: String?

    public init(id: Int? = nil, host: String? = nil, remotePath: String? = nil, localPath: String? = nil) {
        self.id = id
        self.host = host
        self.remotePath = remotePath
        self.localPath = localPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case host
        case remotePath
        case localPath
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(host, forKey: .host)
        try container.encodeIfPresent(remotePath, forKey: .remotePath)
        try container.encodeIfPresent(localPath, forKey: .localPath)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RemotePathMappingResource: Identifiable {}
