//
// RenameMovieResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RenameMovieResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var movieId: Int?
    public var movieFileId: Int?
    public var existingPath: String?
    public var newPath: String?

    public init(id: Int? = nil, movieId: Int? = nil, movieFileId: Int? = nil, existingPath: String? = nil, newPath: String? = nil) {
        self.id = id
        self.movieId = movieId
        self.movieFileId = movieFileId
        self.existingPath = existingPath
        self.newPath = newPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case movieId
        case movieFileId
        case existingPath
        case newPath
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(movieId, forKey: .movieId)
        try container.encodeIfPresent(movieFileId, forKey: .movieFileId)
        try container.encodeIfPresent(existingPath, forKey: .existingPath)
        try container.encodeIfPresent(newPath, forKey: .newPath)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RenameMovieResource: Identifiable {}
