//
// RescanAfterRefreshType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RescanAfterRefreshType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case always = "always"
    case aftermanual = "afterManual"
    case never = "never"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
