//
// RootFolderResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RootFolderResource: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var path: String?
    public var accessible: Bool?
    public var freeSpace: Int64?
    public var unmappedFolders: [UnmappedFolder]?

    public init(id: Int? = nil, path: String? = nil, accessible: Bool? = nil, freeSpace: Int64? = nil, unmappedFolders: [UnmappedFolder]? = nil) {
        self.id = id
        self.path = path
        self.accessible = accessible
        self.freeSpace = freeSpace
        self.unmappedFolders = unmappedFolders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case path
        case accessible
        case freeSpace
        case unmappedFolders
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(accessible, forKey: .accessible)
        try container.encodeIfPresent(freeSpace, forKey: .freeSpace)
        try container.encodeIfPresent(unmappedFolders, forKey: .unmappedFolders)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RootFolderResource: Identifiable {}
