//
// SourceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SourceType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case tmdb = "tmdb"
    case mappings = "mappings"
    case user = "user"
    case indexer = "indexer"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
