//
// TMDbCountryCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TMDbCountryCode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case au = "au"
    case br = "br"
    case ca = "ca"
    case fr = "fr"
    case de = "de"
    case gb = "gb"
    case _in = "in"
    case ie = "ie"
    case it = "it"
    case nz = "nz"
    case ro = "ro"
    case es = "es"
    case us = "us"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
