//
// TrackedDownloadState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TrackedDownloadState: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case downloading = "downloading"
    case importblocked = "importBlocked"
    case importpending = "importPending"
    case importing = "importing"
    case imported = "imported"
    case failedpending = "failedPending"
    case failed = "failed"
    case ignored = "ignored"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
