//
// TrackedDownloadStatusMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrackedDownloadStatusMessage: Sendable, Codable, ParameterConvertible, Hashable {

    public var title: String?
    public var messages: [String]?

    public init(title: String? = nil, messages: [String]? = nil) {
        self.title = title
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(messages, forKey: .messages)
    }
}

