//
// UnmappedFolder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UnmappedFolder: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: String?
    public var path: String?
    public var relativePath: String?

    public init(name: String? = nil, path: String? = nil, relativePath: String? = nil) {
        self.name = name
        self.path = path
        self.relativePath = relativePath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case path
        case relativePath
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(relativePath, forKey: .relativePath)
    }
}

