//
// UpdateChanges.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateChanges: Sendable, Codable, ParameterConvertible, Hashable {

    public var new: [String]?
    public var fixed: [String]?

    public init(new: [String]? = nil, fixed: [String]? = nil) {
        self.new = new
        self.fixed = fixed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case new
        case fixed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(new, forKey: .new)
        try container.encodeIfPresent(fixed, forKey: .fixed)
    }
}

